name: CI-CD

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  ci:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Obter o código do projeto
        uses: actions/checkout@v4

      - name: Autenticar no Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Construção e envio da imagem Docker
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ${{ vars.DOCKERHUB_USERNAME }}/conversao-distancia:latest
            ${{ vars.DOCKERHUB_USERNAME }}/conversao-distancia:v${{ github.run_number }}

  cd:
    runs-on: [self-hosted, linux, x64]
    needs: [ci]
    timeout-minutes: 5
    permissions:
      id-token: write
      contents: read
      actions: read
    steps:
      - name: Obter o código do projeto
        uses: actions/checkout@v4

      # - name: Autenticar na AWS
      #   uses: aws-actions/configure-aws-credentials@v4
      #   with:
      #     aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
      #     aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      #     aws-region: us-east-1
      # - name: Configurar o kubectl
      #   run: aws eks update-kubeconfig --name eks-aula

      - name: Instala kubectl no runner
        shell: bash
        run: |
          curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
          sudo install -o root -g root -m 0755 kubectl /usr/local/bin/kubectl

      # - name: Configura o contexto do Kubernetes
      #   uses: azure/k8s-set-context@v1
      #   with:
      #     method: kubeconfig
      #     kubeconfig: ${{ secrets.KUBECONFIG_GITHUB_SA }}
      #     context: github-sa-context

      - name: Configura o contexto do Kubernetes
        run: | 
          mkdir -p $HOME/.kube
          echo "${{ secrets.KUBECONFIG_GITHUB_SA }}" > $HOME/.kube/config

      - name: Deploy dos manifestos no Kubernetes
        uses: Azure/k8s-deploy@v5
        with:
          namespace: default
          manifests: |
              ./k8s/deployment.yaml
          images: |
              ${{ vars.DOCKERHUB_USERNAME }}/conversao-distancia:v${{ github.run_number }}
